// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXg8z5mKgg3NDDup3GVrIxAorwHuzpEd0',
    appId: '1:969705744016:web:c82af9a9bf970cbde31a15',
    messagingSenderId: '969705744016',
    projectId: 'fitlife-9000e',
    authDomain: 'fitlife-9000e.firebaseapp.com',
    storageBucket: 'fitlife-9000e.appspot.com',
    measurementId: 'G-F95WY611XL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBl1AvAgst4r2LLPHFq66Bo2Xun4crxP14',
    appId: '1:969705744016:android:032bc644772b851ce31a15',
    messagingSenderId: '969705744016',
    projectId: 'fitlife-9000e',
    storageBucket: 'fitlife-9000e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDe8drGVZEBCZUA9Sym_fBRooSbDAOUPj4',
    appId: '1:969705744016:ios:60f18cfbe4d5448be31a15',
    messagingSenderId: '969705744016',
    projectId: 'fitlife-9000e',
    storageBucket: 'fitlife-9000e.appspot.com',
    iosClientId: '969705744016-1d9ag8hpv7lvoiktnf1a4ildtb8jv5rc.apps.googleusercontent.com',
    iosBundleId: 'com.fitlife.fitlife',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDe8drGVZEBCZUA9Sym_fBRooSbDAOUPj4',
    appId: '1:969705744016:ios:60f18cfbe4d5448be31a15',
    messagingSenderId: '969705744016',
    projectId: 'fitlife-9000e',
    storageBucket: 'fitlife-9000e.appspot.com',
    iosClientId: '969705744016-1d9ag8hpv7lvoiktnf1a4ildtb8jv5rc.apps.googleusercontent.com',
    iosBundleId: 'com.fitlife.fitlife',
  );
}
